replicaCount: 1

app:
  serverPort: '6060'
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi

image:
  repository: 795953128386.dkr.ecr.us-west-2.amazonaws.com
  snapshot: false
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ''
  externalIPs: []
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  type: NodePort
  port: 6060
  nodePort: ''

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - qa-mock-adapter.local

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
